<?php

/**
 * Implements hook_menu().
 */
function islandora_uiig_edit_metadata_menu() {
  $items = array();

  // Scan all form associations to build edit links.
  module_load_include('inc', 'xml_form_builder', 'includes/associations');
  module_load_include('inc', 'islandora', 'includes/utilities');
  $associations = xml_form_builder_get_associations();
  $dsids_to_include = array();
  foreach ($associations as $association) {
    if (!isset($dsids_to_include[$association['dsid']])) {
      $dsids_to_include[$association['dsid']] = array($association['content_model']);
    }
    else {
      $dsids_to_include[$association['dsid']][] = $association['content_model'];
    }
  }

  foreach($dsids_to_include as $dsid => $cmodels) {
    $items['islandora/object/%islandora_object/edit_' . $dsid] = array(
      'title' => t('Edit Metadata'),
      'page callback' => 'islandora_uiig_edit_metadata_edit_datastream',
      'page arguments' => array(2, $dsid),
      'type' => MENU_LOCAL_TASK,
      'access callback' => 'islandora_uiig_edit_metadata_edit_datastream_access',
      'access arguments' => array(2, $dsid, $cmodels),
    );
  }
  return $items;
}


/**
 * Callback to edit the datastream.
 */
function islandora_uiig_edit_metadata_edit_datastream($object, $dsid) {
  if (isset($object[$dsid])) {
    module_load_include('inc', 'islandora', 'includes/datastream');
    return islandora_edit_datastream($object[$dsid]);
  }
  else {
    // No edit implementations.
    drupal_set_message(t('This datastream does not exist.'));
    drupal_goto("islandora/object/{$object->id}/manage/datastreams");
  }
}

/**
 * Access callback for editing datastreams also checks if datastream is present.
 */
function islandora_uiig_edit_metadata_edit_datastream_access($object, $dsid, $cmodels) {
  if (!isset($object[$dsid])) {
    return FALSE;
  }
  elseif (count(array_intersect($object->models, $cmodels)) > 0) {
    return islandora_datastream_access(ISLANDORA_METADATA_EDIT, $object[$dsid]);
  }
}
